### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by 0z4ck** [izgzhen/java2smali#1]
downloaded from the [release tab](https://github.com/izgzhen/java2smali/releases/download/1.0/dist.zip)

environment:  Windows10Home/WSL/Ubuntu18.04/open-jdk-8-headless/

full stacktrace:
``` 
$ ./java2smali test.java
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
        at edu.washington.cs.java2smali.App.main(App.kt:16)
$
$ java -jar java2smali-1.0-SNAPSHOT.jar test.java
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
        at edu.washington.cs.java2smali.App.main(App.kt:16)
```

**Comment by izgzhen** [comment]
Thanks for reporting this. I can reproduce the problem and I've fixed the released zip.
